### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by porterhar** [rozek1997/otodom_scrapper#4]
When I am trying to use this scrapper i get this error. Can anyone help me with this issue?

Scrapper was launched
Creating dirs
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 128, in main
    getAllOffer()  # run scraper
  File "main.py", line 51, in getAllOffer
    s, offersQuantity = getAllPageOffer(mainURL)
  File "/home/porterhar/otodom-scrapper/src/scrapping.py", line 99, in getAllPageOffer
    offersQuantity = int(htmlPage.find('div', class_='offers-index').find('strong').text)  # convert text to string
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by skyrrt** [comment]
Yeah, this bothers me too. Can you do anything about it? @rozek1997

**Comment by mkratiuk-analytics** [comment]
Same here guys, any luck solving the problem?

**Comment by kjurzynski** [comment]
A bit of a necro on my part, but the div classes on the website are now all over the place. 

Changing `line 99` in function `scrapping.py` that throws the error to finding the correct line using an attribute instead of class: 

`offersQuantity = int(re.findall(r"\d+", htmlPage.find('span', attrs={'data-sentry-component': 'ItemsCounter'}).get_text(strip=True))[-1])` 

has allowed me to scrape the actual number of offers found... however all the other parts of the code also need changing in this way and more errors will come. The question then becomes if they change this periodically or dynamically since the classes names do sound like gibberish, in which case the code would need updating every time it is changed, or maybe some other clever way of coding around it that I am not currently aware of.

I will be attempting to update the code for the current website, but it remains to be seen if there will be any success since they deliberately make it illegible.
